Create LICENSE
ChatHubLab/chathub-app pull request #1
Opened 2023-10-16 18:06 UTC by Jesse205

2023-10-17 17:22 UTC, dingyi222666 commented
app 这里直接用 apache license 就可以了。

2023-10-17 17:22 UTC, dingyi222666 requested changes
切换到 apache license

2023-10-17 19:42 UTC, Jesse205 commented
才发现[chathub](https://github.com/ChatHubLab/chathub)用的是AGPL，这样不会传染到这个app吗 <img src="https://github.com/ChatHubLab/chathub-app/assets/51242302/0c100feb-5830-443a-86cd-af6aa320de43" alt="shounuehuaji" height="24"/>

2023-10-18 03:47 UTC, dingyi222666 commented
> 切换到 apache license



> 才发现[chathub](https://github.com/ChatHubLab/chathub)用的是AGPL，这样不会传染到这个app吗 <img alt="shounuehuaji" height="24" src="https://user-images.githubusercontent.com/51242302/275979233-0c100feb-5830-443a-86cd-af6aa320de43.png">

后续会独立出来 chathub 的 server api，这块会是 LGPL。通过 API 引用没问题

2023-10-18 03:50 UTC, dingyi222666 reviewed
ok

2023-10-18 03:50 UTC, dingyi222666 approved these changes

2023-10-18 03:50 UTC, merged